server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-89572833.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaf8p4kqrVRHrKix5d7
            client-secret: E1iO88oK0x-xIgrxqT_JwesKdMBdeNYbEqCEiuQn4kMTFpRmX0oXuFsQt99sVE4X

        provider:
          okta:
            issuer-uri: https://dev-89572833.okta.com/oauth2/default




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

    retry:
      instances:
        ratingHotelService:
          max-attempts: 3
          wait-duration: 5s



    rateLimiter:
      instances:
        userRateLimiter:
          limit-refresh-period: 4s
          limit-for-period: 2
          timeout-duration: 0s


okta:
  oauth2:
    issuer: https://dev-89572833.okta.com/oauth2/default
    audience: api://default





